export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_PET_BEGIN = 'CREATE_PET_BEGIN'
export const CREATE_PET_SUCCESS = 'CREATE_PET_SUCCESS'
export const CREATE_PET_ERROR = 'CREATE_PET_ERROR'

export const GET_PETS_BEGIN = 'GET_PETS_BEGIN'
export const GET_PETS_SUCCESS = 'GET_PETS_SUCCESS'

export const SET_EDIT_PET = 'SET_EDIT_PET'
export const EDIT_PET_BEGIN = 'EDIT_PET_BEGIN'
export const EDIT_PET_SUCCESS = 'EDIT_PET_SUCCESS'
export const EDIT_PET_ERROR = 'EDIT_PET_ERROR'

export const DELETE_PET_BEGIN = 'DELETE_PET_BEGIN'

export const GET_USERS_BEGIN = 'GET_USERS_BEGIN'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
